name: Run-CodeBuild-sys-prd-cicd

on:
  workflow_dispatch:

env:
  PROJECT_NAME: sys-prd-codebuild-project-cicd
  BUILDSPEC: ./buildspec_sys_prd_cicd.yml

jobs:
  run-codebuild:
    runs-on: ubuntu-larger-runner-latest
    env : 
      allow_users: ${{ secrets.ALLOWED_USERS }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: ${{ contains(env.allow_users, github.actor) }} 
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::584729548090:role/gen-prd-role-s-github-actions-oidc
      - run: aws sts get-caller-identity

      - name: Configure AWS Credentials2
        if: ${{ contains(env.allow_users, github.actor) }} 
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-external-id: ${{ secrets.EXTERNAL_ID_PRD }}
          role-to-assume: arn:aws:iam::{aws-account-id}:role/sys-prd-role-s-github-actions-deploy
          role-duration-seconds: 900
      - run: aws sts get-caller-identity

      - name: Run CodeBuild Project - cicd
        if: ${{ contains(env.allow_users, github.actor) }} 
        uses: aws-actions/aws-codebuild-run-build@v1.0.6
        with:
          project-name: ${{ env.PROJECT_NAME }}
          buildspec-override: ${{ env.BUILDSPEC }}

      - name: echo commit-sha-1
        run: |
          echo ${{ github.sha }}
